### ISSUE TITLE
Reports double line height in Chrome

### ISSUE THREAD

**Issue by lolmaus** [twolfson/line-height#4]
Hi.

I'm trying to display a tooltip below the caret of a text field. I'm using [another library](https://github.com/component/textarea-caret-position/) to detect caret position. That library reports coordinates of caret's top. To position the tooltip below the caret, I need subj.

My problem is that subj reports different result depending on the browser. In Firefox 51, the result is correct, but on Chrome 57 it is exactly two times larger than expected.

**Comment by twolfson** [comment]
I haven't touched this repo in a really long time but I'm not 100% confident this fully worked across all browsers. Looking at the testling matrix, there were definitely failures in Chrome. Do you know if this was working with Chrome 56?

**Comment by lolmaus** [comment]
Same problem in Chrome 56.

**Comment by twolfson** [comment]
Alright, going to take a shot at stabilizing this repo (i.e. moving from `testem` to Karma, upgrading `browserify`, moving from Testling to Travis CI + Sauce Labs) to better triage the problem

**Comment by lolmaus** [comment]
Thx! I'm happy to help. Will need some guidance, though.

**Comment by twolfson** [comment]
I got the test suite running locally in Karma with Chrome 56 and it seems to be fully passing. Could you provide a sample gist for us to reproduce the issue?

**Comment by lolmaus** [comment]
Looks like the problem is exclusive to `<textarea>`: http://jsbin.com/nuzikut/1/edit?html,js,console

PS That snippet crashes for me in Firefox. But that's a separate issue.

**Comment by twolfson** [comment]
Great, thanks =) I'm able to reproduce the issue in Chrome via that page :+1:

**Comment by twolfson** [comment]
We were able to find the issue, patch it, and released it in `0.3.0`.

The issue was an unstyled `textarea` has line-height of `normal`. For `normal` line heights, we regenerate a similar node and measure its offset height. For a textarea, it has multiple rows and default border/padding so we need to set it to 1 row as well as strip those properties

**Comment by twolfson** [comment]
Thanks for the quick responses and providing a good example =)

**Comment by lolmaus** [comment]
Thank YOU for maintaining an old lib and providing a fix so promptly! :bow:

I've already tried the fix and it works. :+1: 

PS Can you please have a look if my example crashes for you in Firefox?

**Comment by twolfson** [comment]
I get a script error in JSBin but then when I enable the HTML panel it `console.log's` fine. I'm guessing Firefox is being finnicky about not having a visible DOM to do computed style on

**Comment by lolmaus** [comment]
You're right. Thx again.
