### ISSUE TITLE
When the measured DOM is canvas, the calculated value is wrong

### ISSUE THREAD

**Issue by hzmming** [twolfson/line-height#7]
Because canvas has a default height, 150.

```javascript
_node = document.createElement('canvas');
document.body.append(_node);
_node.offsetHeight === 150 // true
```
How to resolve this problem? Maybe just turn the temporary node `canvas` into `span` or any other element ?

**Comment by twolfson** [comment]
I don't understand the issue. If `<canvas>` has a default height of 150, you're adding it without modification to the DOM, and retrieving the value of 150, then what is the issue?

**Comment by hzmming** [comment]
Sorry, i didn't make it clear.
I mean,
```html
<span id="testSpan">hello</span>
<div id="testDiv">world</div>
<canvas id="testCanvas"></canvas>

<script>
const testSpan = document.querySelector('#testSpan');
const testDiv = document.querySelector('#testDiv');
const testCanvas = document.querySelector('#testCanvas');

// my chrome browser
lineHeight(testSpan) // 22
lineHeight(testDiv) // 22
lineHeight(testCanvas) // 150    It's different from others
</script>
```
So I think maybe we should give special treatment to canvas ?

**Comment by twolfson** [comment]
That looks like everything is working as expected still =/ The intended user case of this library was to get equivalent line heights for `inline` elements compared to their `block` or `inline-block` counterparts

e.g. If I place a `<span>` next to `<canvas>`, how can I make the `<span>` have the same `line-height` so the text is properly vertically centered?

The answer in this case would be `line-height: 150px`

---

Closing this issue as `wontfix` and `question`
